### PR TITLE
TG-72-69: Admin

### PR DESCRIPTION
**Pull request by GinaSchP**

### CODE REVIEW

**Review by ilcosme — APPROVED** [review]
Good to go!

**Review by fernandocarbone1 — APPROVED** [review]

**Comment by karu-ams** [comment]
chrome-capture-2022-5-2

**Comment by karu-ams** [comment]
## Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-28admin-basp-m2022.vercel.app/

**Test Results: Failed ⚠️**

Bugs found:

1.  The grey color of the button may confuse the user, it appears to be disabled. In addition, the button action can only be press by clicking right on the text. Outside the red rectangle delimited in the image below, the link in the button doesn't work, just inside the red box.

GinaBug1
 
2. "Active" should be a checkbox or dropdown because this way the user could not understand which data is required in the field.

GinaBug2
 
3. When submitting the form with an error in the validation, a message is shown. When you close this message, it redirects you to the admins table list. This should not happen, the user should be able to correct the mistakes in the form fields.
GinaBug2b
GinaBug2c
GinaBug2d
GinaBug2a

4. Same as bug #1, please check if the link works in all the button.
Ginabug4

5. Delete button seems to be a string when hover the mouse, maybe it could be confusing. If possible, another mouse cursor could be fine. The Delete warning is correctly shown, but when you delete, a message of successful could be shown too. 
Ginabug6

Ginabug6b

Ginabug6a

Very good work! Sorry it takes a while, I had some Internet issues...

**Review by karu-ams — CHANGES_REQUESTED** [review]
Gina, please check the PR Review commented recently. Some functionalities could be improved.

**Comment by RominaRIP** [comment]
## Test result (TG-69)

Tested locally on https://alfonso-trackgenix-app-git-feature-tg-72-69admins-basp-m2022.vercel.app/admins

Test Results: Failed ⚠️

Bugs found:

**1. Admin can't be created. This error message pops up when the user fills the inputs and tries to create the admin:**

admin-create-error

Also, there's no message under the input fields that makes the user know which field is not valid.
Test data used:
- First name: Jane
- Last Name: Doe
- Email: rose@radiumrocket.com
- Password: BaSP2022
- Active: active

Suggestion: There are several layout bugs. For example, the form inputs in the 'Add new Admin' feature are not well aligned. You can work in the way it is displayed if you have enough time.

**2. There should be a button to come back to the list of admins from the creating form**

**3. On editing, form contains previous info as a placeholder. The content should be a text to edit.**

admin-edit-placeholder

**4. There's not button to cancel the action of edit an Admin, in the 'Edit Admin' form screen.**

**5. The overlay displayed when the user clicks 'Submit' button in the edit admin form is empty:**

admin-edit-empty-message

**6. Once the user clicks on 'close' button of the overlay described in the item before and then goes back to the 'Admins list' screen using the browser button to go back, the Admin selected to edit is not modified with the new data filled.**
Test data used (Id: 629a8334fbc98e77f4eb2128):
- Last Name: constanzaaa

**7. When the user refreshes the list of admins, the admin selected previously to edit is no longer displayed on the list (Id: 629a8334fbc98e77f4eb2128).**

**8. [Suggestion] The alert message displayed when the user tries to delete an admin should be redacted differently.**

For example: 'Are you sure you want to delete the selected admin?' or 'Are you sure you want to delete the admin with the Id: xxxxxxxxxx?'
Actual behavior:

admin-delete-alert

**9. The delete button should be improved. The cursor behavior changes when hovers the red cross as if it were a text format data, instead of an icon or a button.**

**Comment by RominaRIP** [comment]
## 2nd testing results

Tested locally on https://alfonso-trackgenix-app-git-feature-tg-72-69admins-basp-m2022.vercel.app/admins

Test Results: Passed ✅

Good job, Gina! Everything is working as expected.

Tested:
- Add route on Layout Component
- Create Form
- Add feature
- On editing, form should contain previous info
- Edit feature
- Success message for Add or Edit

Test data used:
- First name: Jane
- Last Name: Doe
- Email: [rose@radiumrocket.com](mailto:rose@radiumrocket.com)
- Password: BaSP2022
- Active: [selected]

**Review by karu-ams — APPROVED** [review]

**Pull request merged**
