### PR TITLE
TG-107: Redux in superadmin

### PR DESCRIPTION
**Pull request by nicolascostanza**
CRUD with states brought from the redux store

### CODE REVIEW

**Review by martinalbrnz — APPROVED** [review]
LGTM!

**Review by ilcosme — APPROVED** [review]
Good to go!

**Review by karu-ams — DISMISSED** [review]
## Testing Results
_Tested locally on https://alfonso-trackgenix-kotlcy1z9-basp-m2022.vercel.app/_

Test Results: PASS ✅ READY TO MERGE

**Review by martinalbrnz — APPROVED** [review]
LGTM AGAIN :D

**Review by FefeTroanes — APPROVED** [review]
ken blam

**Review by karu-ams — APPROVED** [review]
## Testing Results
_Tested locally on https://alfonso-trackgenix-kotlcy1z9-basp-m2022.vercel.app/_

Test Results: PASS ✅ READY TO MERGE

**Review by FefeTroanes — APPROVED** [review]
lgtm

**Pull request merged**
