### PR TITLE
TG-128: Projects form validations and React lazy

### PR DESCRIPTION
**Pull request by martinalbrnz**
- Validations should work now, showing a message with the error, acting onBlur
- If there is an error, the app should not make an api call
- Rest of functionalities should remain the same
- React lazy should split the code bundles on smaller parts, so it can improve initial loading time

### CODE REVIEW

**Review by nicolascostanza — COMMENTED** [review]
genial

**Review by FefeTroanes — APPROVED** [review]
Gud shob!

**Comment by Clarosluciano** [comment]
# Test result:

Locally tested on: https://alfonso-trackgenix-dvawzwc0i-basp-m2022.vercel.app/projects
Validations: fail
Functionalities: 

# Bugs found:
1. In the inputs "start date" and "end date" you can put any date. Validation error msg is not triggered:
image
**Expected behavior:** Validations should stop the entry of that erroneous information.

2. Form elements are close together:
image
**Expected behavior:** There is a certain separation between each element maintaining a symmetrical visual flow.

3. When a project is deleted, and it is the only project in that tab, the tab remains empty and is not automatically deleted. Even if the page is reloaded, the tab is still there:
image
**Expected behavior:** The empty tab should be removed automatically.

**Review by GinaSchP — DISMISSED** [review]

**Review by nicolascostanza — APPROVED** [review]

**Review by GinaSchP — APPROVED** [review]

**Review by Clarosluciano — APPROVED** [review]
Gj!

**Pull request merged**
