### PR TITLE
TG-141: implement button to log out session and back to home

### PR DESCRIPTION
**Pull request by javierlazzarini**
Add link in the header to close the session and back the user to home page

### CODE REVIEW

**Review by nicolascostanza — APPROVED** [review]

**Review by martinalbrnz — APPROVED** [review]
LGTM!

**Comment by Clarosluciano** [comment]
# Test results:
Functionalities: fail

# Bugs found:
1. When clicks on any entity button the login not appear, instead a word "login" appear in the left of the screen
image
2. The logout button redirect to Home but never logged in previously
image
image

**Review by Clarosluciano — APPROVED** [review]
# Test result:
Logout: pass

PD: when the profile information is edited it is not updated immediately, the page must be reloaded to be displayed on the screen.

**Review by FefeTroanes — APPROVED** [review]
listo

**Pull request merged**
